direction: right

Client: "" {
  shape: circle
  icon: https://icons.terrastruct.com/aws%2F_General%2FUsers_light-bg.svg
}

app: Web Server {
  grid-rows: 1
  icon: https://icons.terrastruct.com/azure%2FWeb%20Service%20Color%2FApp%20Services.svg
}

gateway: Azure Service Bus {
  icon: https://icons.terrastruct.com/azure%2FIntegration%20Service%20Color%2FAzure%20Service%20Bus.svg
}

server: Service {
  grid-rows: 1
  Instance: Instance
  Instance.icon: https://icons.terrastruct.com/dev%2Fcsharp.svg
  Instance1: Instance
  Instance1.icon: https://icons.terrastruct.com/dev%2Fcsharp.svg
  Instance2: Instance
  Instance2.icon: https://icons.terrastruct.com/dev%2Fcsharp.svg
}

Client -- app

app -- gateway

gateway -- server
